//
// StateInformation.swift
// Created by Joey Jarosz on 12/14/25.
// Copyright (c) 2025 hot-n-GUI, LLC. All rights reserved.
//

import Foundation
import FoundationModels

/// Represents comprehensive information about a US state
/// Generated by FoundationModels using the @Generable macro for type-safe responses
@Generable
struct StateInformation: Sendable {
    /// The official name of the state (e.g., "California")
    var stateName: String

    /// The state's capital city (e.g., "Sacramento")
    var capital: String

    /// The official state bird (e.g., "California Valley Quail")
    /// May be nil if information is not available
    var stateBird: String?

    /// The official state flower or plant (e.g., "California Poppy")
    /// May be nil if information is not available
    var statePlant: String?

    /// Approximate latitude for the state's geographic center
    var centerLatitude: Double

    /// Approximate longitude for the state's geographic center
    var centerLongitude: Double
}

/// Represents the possible states of a query operation
enum QueryState: Equatable {
    case idle
    case loading
    case success(StateInformation)
    case error(String)

    static func == (lhs: QueryState, rhs: QueryState) -> Bool {
        switch (lhs, rhs) {
        case (.idle, .idle), (.loading, .loading):
            return true
        case (.success(let lhsInfo), .success(let rhsInfo)):
            return lhsInfo.stateName == rhsInfo.stateName
        case (.error(let lhsMsg), .error(let rhsMsg)):
            return lhsMsg == rhsMsg
        default:
            return false
        }
    }
}
