import SwiftUI

/// A full-bleed rectangle whose surface is generated by a `[[stitchable]]`
/// fragment shader. Animation is driven by `TimelineView(.animation)` higher
/// up; the `time` value is passed in as a uniform.
struct ShaderCanvas: View {
    let kind: ShaderDemo.Kind
    let time: Float

    var body: some View {
        Rectangle()
            .visualEffect { effect, proxy in
                let w = Float(proxy.size.width)
                let h = Float(proxy.size.height)
                return effect.colorEffect(
                    ShaderLibrary[dynamicMember: kind.functionName](
                        .float(time),
                        .float2(w, h)
                    )
                )
            }
    }
}
